export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const SEARCH_POST = "SEARCH_POST";
export const POST_REQUEST = "POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCESS";
export const POST_REQUEST_FAILURE = "POST_REQUEST_FAILURE";
